solver: "cgp"
seed: [ 0,1,2,3,4,5,6,7,8,9 ]
n_nodes: 50
n_individuals: 100
p_mut_outputs: 0.3
p_mut_inputs: 0.1
p_mut_functions: 0.1
n_generations: 1333
selection:
  elite_size: 10
  type: "tournament"
  tour_size: 3
survival: "truncation"
crossover: False
run_name: "difficult_parallel_long"
obs_size: 8
start_port: 25000
levels: "many_pipes,many_enemies,many_blocks"
adaptive: False
levels_seeds: "0;2;4"